version: 2

models:

  - name: dim_location
    columns:
      - name: location_key
        description: The surrogate key of the addressid
        tests:
          - not_null
          - unique
      
    

      - name: country
        description: The conutry name

      - name: city
        description: The city name

      - name: latitude
        description: latitude from API
      
      - name: longitude
        description: longitude from API

        
    
  - name: dim_date
    description: "Date dimension"
   

  - name: dim_weather_condition
    

  - name: fact_sun_times_forecast
  - name: fact_sun_times_history
  - name: fact_weather_params_forecast
  - name: fact_weather_params_history

    